### ISSUE TITLE
db error using unraid template

### ISSUE THREAD

**Issue by MichaelGoedken** [RoastSlav/quickdrop#29]
Hello, 

Trying to install for the first time, can you help with the errors I'm getting? Seems like there's a db issue:

[quickdrop.log](https://github.com/user-attachments/files/19376299/quickdrop.log)

**Comment by RoastSlav** [comment]
It's not an issue with your setups. I found the problem and I'm releasing a patch version right now. You can update you docker images and try again. But make sure to remove the old db from your prevous attempts. watch out for 1.4.1 version

**Comment by boomam** [comment]
Redeployed (k8s deployment) with v1.4.1, issue is now resolved.

**Comment by MichaelGoedken** [comment]
However in the GUI still shows version 1.4.0

<img width="296" alt="Image" src="https://github.com/user-attachments/assets/53b8bb0a-268b-4a90-8f63-7c0f31562f6c" />

**Comment by RoastSlav** [comment]
I wanted to release a patch quick and forgot to update it 😅
